### ISSUE TITLE
Wallet will be exhausted in certain conditions

### ISSUE THREAD

**Issue by rlapao** [unl1k3ly/AnchorHODL#8] opened 2021-06-27 19:19 UTC
Thanks for the script unl1k3ly! Hope it will get even better.

I believe this is what may have happened with @conradjohnson (https://github.com/unl1k3ly/AnchorHODL/issues/2) (maybe not). 

On June 21st with the market volatility my loan triggered a buy. but the repay transaction for some reason didn't went through (insufficient funds: insufficient account funds; 11862968uusd < 33429895uusd: failed to execute message; message index: 0) although it was created by the script:

Looking into the logs:

```
21-06-2021 21:18:50  Left until trigger: 0.05%, Current at: 84.95%, Triggering at: 85%, Borrow Limit target 80%.
21-06-2021 21:19:19  REPAYING ... Left until trigger: -0.1%, Current at: 85.10%, Triggering at: 85%, Borrow Limit target: 80%.
21-06-2021 21:19:19  Paying loan from 32 UST leftover in the wallet
21-06-2021 21:19:50  REPAYING ... Left until trigger: -0.1%, Current at: 85.10%, Triggering at: 85%, Borrow Limit target: 80%.
21-06-2021 21:19:50  Paying loan from 32 UST leftover in the wallet
21-06-2021 21:20:19  REPAYING ... Left until trigger: -0.08%, Current at: 85.08%, Triggering at: 85%, Borrow Limit target: 80%.
21-06-2021 21:20:19  Paying loan from 32 UST leftover in the wallet
21-06-2021 21:20:50  Left until trigger: 0.21%, Current at: 84.79%, Triggering at: 85%, Borrow Limit target 80%.
.......
21-06-2021 21:34:50  REPAYING ... Left until trigger: -0.02%, Current at: 85.02%, Triggering at: 85%, Borrow Limit target: 80%.
21-06-2021 21:34:50  Paying loan from 32 UST leftover in the wallet
```

Since the script runs each 30 seconds, 3 repay transactions were generated, but none was completed (due to insufficient funds which is weird because 1) I remember having funds on the wallet ~50 usd and 2) the logs says that is repaying from the wallet).

This went like that creating transactions during some time, until it drained all my wallet funds :P Becaus each of these transactions created by the script had a tx fee of 1.679895 UST

After 21:49:49 (UTC) it started to show logs like this, since the wallet had no more funds and there was no sufficient funds to create the txs:

```
21-06-2021 21:49:49  REPAYING ... Left until trigger: -0.03%, Current at: 85.03%, Triggering at: 85%, Borrow Limit target: 80%.
21-06-2021 21:49:49  Paying loan from 32 UST leftover in the wallet
21-06-2021 21:49:51  Status 404 - Tx: RPC error -32603 - Internal error: tx (95.........E1) not found
21-06-2021 21:49:51  check_tx_info(95.......E1) was not found ... Maybe something went wrong ?
```

Looking into the repay logs it gives the impression that the txs were getting through but looking to each of them they failed.

```
21-06-2021 21:19:25  Loan Repaid!!! Repay Amount: $32.00, triggered at: 85.10% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/03........9D
21-06-2021 21:19:58  Loan Repaid!!! Repay Amount: $32.00, triggered at: 85.10% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/22........D0
21-06-2021 21:20:25  Loan Repaid!!! Repay Amount: $32.00, triggered at: 85.08% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/05........20
21-06-2021 21:34:57  Loan Repaid!!! Repay Amount: $32.00, triggered at: 85.02% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/6C........6E
21-06-2021 21:47:57  Loan Repaid!!! Repay Amount: $32.00, triggered at: 85.18% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/B8........FB
21-06-2021 21:48:31  Loan Repaid!!! Repay Amount: $33.00, triggered at: 85.20% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/AC........0B
21-06-2021 21:48:57  Loan Repaid!!! Repay Amount: $33.00, triggered at: 85.22% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/28........6A
21-06-2021 21:49:30  Loan Repaid!!! Repay Amount: $33.00, triggered at: 85.23% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/05........28
21-06-2021 21:49:51  TX 404 ... Loan Repaid!!! Repay Amount: $32.00, triggered at: 85.03% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/95........E1
21-06-2021 21:50:22  TX 404 ... Loan Repaid!!! Repay Amount: $32.00, triggered at: 85.03% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/95........E1
21-06-2021 21:50:52  TX 404 ... Loan Repaid!!! Repay Amount: $32.00, triggered at: 85.10% (85% trigger limit). TX: https://finder.terra.money/columbus-4/tx/95........E1
....
```

I'm not quite sure why or how this happened, but it happened solely by the script orders, since I was asleep :P 

Creating multiple txs will eventually drain the wallet, even if they are all failing.

In my case it wasn't that bad since my wallet had little money, but it can be dangerous :P 

Not sure if you can understand what really happened here, since your are more knowledgeable of the code.

**Comment by unl1k3ly** [comment] 2021-06-30 23:12
Hi mate ... Sorry for your bad experience. Does TX have any error in it ? I'm not sure what happened. It surely did not repay as your LVL wasn't getting any better.

for 404 tx it could be simply because tx were not fully processed by the chain, which could happen sometimes when network is busy, however, it would take a few seconds to be successfully (hence I'm running every 30 seconds or so).

That being said, it seems your problem was something else ...  

Were you running from latest ? 

Cheers

**Comment by rlapao** [comment] 2021-07-01 06:28
No worries mate, I was fully aware of the risks, and happy to use your script! :)

I'm attaching a print of the tx, all the others look pretty the same.
![Screenshot 2021-07-01 at 07 13 27](https://user-images.githubusercontent.com/1626181/124074981-2050ef00-da3c-11eb-9d17-2c139cf85ec3.png)

I was running the latest from 16th June, you had a new commit on the 20th, that at the time I hadn't updated to.

From my understanding, so far, it seems that, maybe because of network issues, there were multiple repay txs issued. (I have the schedule for 30 seconds as the default value).

I'm thinking of changing the script to run synchronously, when I have the time :P Or maybe just use the persistent mode (gunicorn) - that should resolve the issue, or maybe always go to the Earn amount instead of the wallet.

I've tried to replicate the issue with testnet but I wasn't able to reproduce the behaviour.

Now I always have less then 10 UST in my wallet so I believe I'm good.

(I'm happy to share more info with you if you want)

Thanks for your reply

**Comment by unl1k3ly** [comment] 2021-07-18 19:42
Hi mate, sorry for delay response here ... I could not reproduce your issue at testnet, however, when col-5 is out for testing I'll modify a bunch and make a better logic for repaying. That being said, that would reduce the risks of repay loops as you experienced. I'm closing this one for now, stay tuned for updates ! cheers !

**Closed** 2021-07-18 19:43 UTC
